# Generated by Django 4.2.25 on 2025-10-28 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_doc', '0041_alter_attachment_id_alter_doc_id_alter_dochistory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHotKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='关键词')),
                ('search_count', models.IntegerField(default=0, verbose_name='搜索次数')),
                ('last_searched_at', models.DateTimeField(auto_now=True, verbose_name='最后搜索时间')),
                ('hot_score', models.FloatField(db_index=True, default=0.0, verbose_name='热度分数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '热门搜索词',
                'verbose_name_plural': '热门搜索词',
                'db_table': 'search_hot_keyword',
                'ordering': ['-hot_score', '-search_count'],
            },
        ),
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, verbose_name='原词')),
                ('synonyms', models.TextField(verbose_name='同义词列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '搜索同义词',
                'verbose_name_plural': '搜索同义词',
                'db_table': 'search_synonym',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(db_index=True, max_length=500, verbose_name='搜索词')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('results_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('search_mode', models.CharField(default='or', max_length=10, verbose_name='搜索模式')),
                ('search_field', models.CharField(default='all', max_length=20, verbose_name='搜索字段')),
                ('elapsed_time', models.IntegerField(default=0, verbose_name='搜索耗时(ms)')),
                ('has_click', models.BooleanField(default=False, verbose_name='是否点击结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='搜索时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='搜索用户')),
            ],
            options={
                'verbose_name': '搜索日志',
                'verbose_name_plural': '搜索日志',
                'db_table': 'search_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query_text', '-created_at'], name='search_log_query_t_5f17a1_idx'), models.Index(fields=['user', '-created_at'], name='search_log_user_id_e36ea2_idx')],
            },
        ),
    ]
