version: '3'
services:
  mrdoc:
    image: zmister/mrdoc:v9.3  # 镜像名称和标签
    volumes:
      - ${PWD}:/app/MrDoc  # 挂载代码目录
    ports:
      - "10086:10086"
    restart: always
    dns:
      - 8.8.8.8
      - 114.114.114.114